/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gwj_jnijava_MainActivity */

#ifndef _Included_com_gwj_jnijava_MainActivity
#define _Included_com_gwj_jnijava_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gwj_jnijava_MainActivity
 * Method:    calladd
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_gwj_jnijava_MainActivity_calladd
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
