/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gwj_clothes_analysisrealize */

#ifndef _Included_com_gwj_clothes_analysisrealize
#define _Included_com_gwj_clothes_analysisrealize
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gwj_clothes_analysisrealize
 * Method:    getinitaladdress
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jint JNICALL Java_com_gwj_clothes_analysisrealize_getinitaladdress
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
